### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by adamhe1993** [LenaShengzhen/AerialRobotics#2]
Ellipsoid.m 第24行是不是应该开根号呢

**Comment by LenaShengzhen** [comment]
In order to speed up the calculation, the square root has been removed at this. It has no effect on judging whether the point is inside the ellipse, and what is affected should be the accuracy calculation of 106 lines of code in LineSegment.m. The next version will take the square root in the accuracy calculation. Thanks for your question.

**Comment by adamhe1993** [comment]
Hi! I want to simulate code myself. Do you mind uploading execution scripts?

**Comment by LenaShengzhen** [comment]
The startup script has been uploaded.

**Comment by adamhe1993** [comment]
Thank you
